Revert temp folder changes.

diff --git a/assignment1/matrix b/assignment1/matrix
--- a/assignment1/matrix
+++ b/assignment1/matrix
@@ -8,10 +8,10 @@
 operation=$1
 params=$#
 fromStdin=0
-tempFilePrefix="_temp_$$"
 
-#Clean up any previous temp files if previous execution was not successful.
-rm -rf _temp_*
+#Create a folder for temporary files. Clean up any previous temp files.
+rm -rf ./temp
+mkdir temp
 
 if [ -t 0 ]; then
     #If there is nothing in stdin, treat second and the third parameters as matrix files.
@@ -22,11 +22,11 @@ else
     fromStdin=1
 
     #Create the temporary file to store the contents of stdin.
-    tempFile="$tempFilePrefix init"
+    tempFile="./temp/$$"
 
     #Write contents of stdin into the temporary file.
     while read -r line ; do
-        echo $line >> "$tempFile"
+        echo $line >> $tempFile
     done
 
     #Point matrix1 to the temporary file.
@@ -35,13 +35,13 @@ fi
 
 #Checks that matrix 1 file is readable before attempting to read it.
 checkMatrix1File() {
-    if ! [ -a "$matrix1" ];
+    if ! [ -a $matrix1 ];
     then
         echo "$matrix1 does not exist!" >&2
         exit 500
     fi
 
-    if ! [ -r "$matrix1" ];
+    if ! [ -r $matrix1 ];
     then
         echo "$matrix1 is not readable!" >&2
         exit 500
@@ -50,13 +50,13 @@ checkMatrix1File() {
 
 #Same as above ^^.
 checkMatrix2File() {
-    if ! [ -a "$matrix2" ];
+    if ! [ -a $matrix2 ];
     then
         echo "$matrix2 does not exist!" >&2
         exit 500
     fi
 
-    if ! [ -r "$matrix2" ]; then
+    if ! [ -r $matrix2 ]; then
         echo "$matrix2 is not readable!" >&2
         exit 500
     fi
@@ -153,16 +153,16 @@ transpose() {
     count=0
     while read -r row ; do
         count=$(expr $count + 1)
-        tempColFile="$tempFilePrefix transpose_row $count"
-        echo $row >> "$tempColFile"
-    done < "$matrix1"
+        tempColFile="./temp/transpose_row_$count"
+        echo $row >> $tempColFile
+    done < $matrix1
 
     #Until row files are not empty, take the first number from it and put into a column.
     filesNum=$count
     count=0
     for (( ; ; )) ; do
         count=$(expr $count + 1)
-        tempColFile="$tempFilePrefix transpose_row $count"
+        tempColFile="./temp/transpose_row_$count"
         row=""
 
         #This loop will be executing just once because temp row files have only one line.
@@ -170,10 +170,10 @@ transpose() {
             row=$line
             numbers=($line)
             echo -n ${numbers[0]}
-        done < "$tempColFile"
+        done < $tempColFile
 
         #Clear the temp file
-        rm -rf "$tempColFile"
+        rm -rf $tempColFile
 
         #Put all numbers back to the temp file except the first one.
         index=0
@@ -186,7 +186,7 @@ transpose() {
         done
 
         #Write the new string to the temp row file.
-        echo $newRow > "$tempColFile"
+        echo $newRow > $tempColFile
 
         #Update count to start printing out the next row.
         if (( $count == $filesNum )) ; then
@@ -216,20 +216,20 @@ mean() {
         count=0
         for number in $row ; do
             count=$(expr $count + 1)
-            tempColFile="$tempFilePrefix mean_col $count"
-            echo $number >> "$tempColFile"
+            tempColFile="./temp/mean_col_$count"
+            echo $number >> $tempColFile
         done
-    done < "$matrix1"
+    done < $matrix1
 
     #Iterate over temp column files to calculate the mean of each column.
     for ((col=1;col<=$cols;col++)); do
-        tempColFile="$tempFilePrefix mean_col $col"
+        tempColFile="./temp/mean_col_$col"
         sum=0
 
         #Calucalte the sum of all the numbers in the column.
         while read -r num ; do
             sum=$(expr $sum + $num)
-        done < "$tempColFile"
+        done < $tempColFile
 
         if (( $sum == 0 )); then
             average=0
@@ -260,13 +260,13 @@ add() {
         for number in $row ; do
             numbers="$numbers $number"
         done
-    done < "$matrix1"
+    done < $matrix1
 
     while read -r row ; do
         for number in $row ; do
             numbers="$numbers $number"
         done
-    done < "$matrix2"
+    done < $matrix2
 
     #Convert the numbers string into an array.
     numArray=($numbers)
@@ -319,10 +319,10 @@ multiply() {
         count=0
         for number in $row ; do
             count=$(expr $count + 1)
-            tempColFile="$tempFilePrefix multiply_col $count"
-            echo $number >> "$tempColFile"
+            tempColFile="./temp/multiply_col_$count"
+            echo $number >> $tempColFile
         done
-    done < "$matrix2"
+    done < $matrix2
 
     #For every row in matrix1.
     while read -r row ; do
@@ -332,11 +332,11 @@ multiply() {
         #Multiply current m1 row by every m2 column.
         for (( col=1; col<=m2Cols; col++ )) ; do
             #Get an array of numbers in this m2 column.
-            tempColFile="$tempFilePrefix multiply_col $col"
+            tempColFile="./temp/multiply_col_$col"
             colNumbers=""
             while read -r num ; do
                 colNumbers="$colNumbers $num"
-            done < "$tempColFile"
+            done < $tempColFile
             colNumbersArray=($colNumbers)
 
             #Multiply every element in m1 row by every element in m2 column and print out the result.
@@ -357,7 +357,7 @@ multiply() {
 
         #Add new line
         echo
-    done < "$matrix1"
+    done < $matrix1
 }
 
 #Invokes the right function based on operation passed as the first parameter to the script.
@@ -380,4 +380,7 @@ case "$1" in
 esac
 
 #Clean up after script execution.
-rm -rf _temp_*
+rm -rf ./temp
+
+#todo: no temp folder
+#todo: all files have process ID
