Use trap to cleanup temp files on errors.

diff --git a/assignment1/matrix b/assignment1/matrix
--- a/assignment1/matrix
+++ b/assignment1/matrix
@@ -10,7 +10,10 @@ params=$#
 fromStdin=0
 tempFilePrefix="_temp_$$_"
 
-#Clean up any previous temp files that might have been generated by previous execution in case there were exceptions.
+#Catch errors and clean up temp files.
+trap "rm -f _temp_*; echo 'Some error occurred, exiting'; exit 1" INT HUP TERM
+
+#Clean up any previous temp files that might have been left for whatever reason.
 rm -rf _temp_*
 
 if [ -t 0 ]; then
@@ -22,7 +25,7 @@ else
     fromStdin=1
 
     #Create the temporary file to store the contents of stdin.
-    tempFile="$tempFilePrefix\init"
+    tempFile="$tempFilePrefix-init"
 
     #Write contents of stdin into the temporary file.
     while read -r line ; do
@@ -153,7 +156,7 @@ transpose() {
     count=0
     while read -r row ; do
         count=$(expr $count + 1)
-        tempColFile="$tempFilePrefix\transpose_row_$count"
+        tempColFile="$tempFilePrefix-transpose_row_$count"
         echo $row >> $tempColFile
     done < $matrix1
 
@@ -162,7 +165,7 @@ transpose() {
     count=0
     for (( ; ; )) ; do
         count=$(expr $count + 1)
-        tempColFile="$tempFilePrefix\transpose_row_$count"
+        tempColFile="$tempFilePrefix-transpose_row_$count"
         row=""
 
         #This loop will be executing just once because temp row files have only one line.
@@ -217,14 +220,14 @@ mean() {
         count=0
         for number in $row ; do
             count=$(expr $count + 1)
-            tempColFile="$tempFilePrefix\mean_col_$count"
+            tempColFile="$tempFilePrefix-mean_col_$count"
             echo $number >> $tempColFile
         done
     done < $matrix1
 
     #Iterate over temp column files to calculate the mean of each column.
     for ((col=1;col<=$cols;col++)); do
-        tempColFile="$tempFilePrefix\mean_col_$col"
+        tempColFile="$tempFilePrefix-mean_col_$col"
         sum=0
 
         #Calucalte the sum of all the numbers in the column.
@@ -320,7 +323,7 @@ multiply() {
         count=0
         for number in $row ; do
             count=$(expr $count + 1)
-            tempColFile="$tempFilePrefix\multiply_col_$count"
+            tempColFile="$tempFilePrefix-multiply_col_$count"
             echo $number >> $tempColFile
         done
     done < $matrix2
@@ -333,7 +336,7 @@ multiply() {
         #Multiply current m1 row by every m2 column.
         for (( col=1; col<=m2Cols; col++ )) ; do
             #Get an array of numbers in this m2 column.
-            tempColFile="$tempFilePrefix\multiply_col_$col"
+            tempColFile="$tempFilePrefix-multiply_col_$col"
             colNumbers=""
             while read -r num ; do
                 colNumbers="$colNumbers $num"
